{% set name = "aiosqlite" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 131bb8056daa3bc875608c631c678cda73922a2d4ba8aec373b19f18c17e7aa3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=2,<4
    - typing-extensions >=4.0
  run:
    - typing_extensions >=4.0
    - typing-extensions >=4.0
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - aiosqlite

about:
  home: https://github.com/omnilib/aiosqlite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: asyncio bridge to the standard sqlite3 module
  description: |
    AsyncIO bridge to the standard sqlite3 module for Python 3.5+.
  dev_url: https://github.com/omnilib/aiosqlite

extra:
  recipe-maintainers:
    - carlodri
